const standardNameList = [
    "MySQL",
    "Redis",
    "MacOS",
    "iPhone",
    "iPad",
    "Java",
    "iOS",
    "GitHub",
    "GitLab",
    "Spring Boot",
    "Spring MVC",
    "Spring Cloud",
    "Spring Data JPA",
    "MyBatis",
    "Hibernate",
    "Oracle",
    "Maven",
    "IoC",
    "DI",
    "AOP",
    "JVM",
    "NoSQL",
    "SSO",
    "CAS",
    "HTTP ",
    "HTTPS ",
    "VS Code",
    "JavaScript",
    "CSS",
    "JSON",
    "API",
    "AJAX",
    "HTML ",
    "JSP",
    "springboot:Spring Boot",
];

export const standardNames = standardNameList.map((str) => {
    return {
        key: new RegExp("\\b" + str + "\\b", "gi"),
        value: str,
    };
});
